name: Deploy (Flex) — ECC Orchestrator (Publish Profile)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permissions not strictly required for publish-profile, but harmless to keep
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Deploy with publish profile (bypasses Flex OneDeploy storage config)
      - name: Azure Functions Deploy (Publish Profile)
        uses: Azure/functions-action@v1
        with:
          app-name: empirecommandcenter-altus-node-staging
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          # Explicitly avoid remote build; not needed for JavaScript functions
          remote-build: false
