name: Deploy (Flex) — ECC Orchestrator (Publish Profile, WebApps Deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Use WebApps Deploy with the publish profile (bypasses the OneDeploy/ZipDeploy quirks)
      - name: Deploy via Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: empirecommandcenter-altus-node-staging
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
